//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File_Upload_Reason
    {
        public int ID { get; set; }
        public string Seat_No { get; set; }
        public string File_Status { get; set; }
        public string Reason { get; set; }
        public string Index_No { get; set; }
    }
}
