//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inspection_Basic_Info
    {
        public int ID { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Index_No { get; set; }
        public string College_Name { get; set; }
        public string Teacher_Name { get; set; }
        public string Contact_No { get; set; }
        public int No_Of_Student { get; set; }
        public int No_Of_System { get; set; }
        public int Active { get; set; }
    }
}
