//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        public int id { get; set; }
        public string Index_No { get; set; }
        public string Seat_No { get; set; }
        public string Name { get; set; }
        public string Mother_Name { get; set; }
        public string Batch { get; set; }
        public string Stream { get; set; }
        public Nullable<int> Div { get; set; }
        public string Paper_ID { get; set; }
        public string Hand { get; set; }
        public Nullable<int> Reschedule_Status { get; set; }
        public string Reschedule_Batch { get; set; }
        public string Reschedule_Paper_ID { get; set; }
        public string Reschedule_Approve_BY { get; set; }
        public string Course { get; set; }
        public string Coll_Add_Student { get; set; }
    }
}
