//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_86to90_Ans
    {
        public string index_no { get; set; }
        public string seat_no { get; set; }
        public string datetime { get; set; }
        public string ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q86Ans { get; set; }
        public string Q87Ans { get; set; }
        public string Q88Ans { get; set; }
        public string Q89Ans { get; set; }
        public string Q90Ans { get; set; }
    }
}
