//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Attendance
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string Seat_no { get; set; }
        public Nullable<System.DateTime> time_time { get; set; }
        public string Batch { get; set; }
        public string MAC { get; set; }
    }
}
