//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_DTT1
    {
        public int ID { get; set; }
        public string Datetime { get; set; }
        public string Index_No { get; set; }
        public string Index_NoN { get; set; }
        public string SYS_No { get; set; }
        public string MAC { get; set; }
        public string Screen_Res { get; set; }
        public string Screen_Res_Change { get; set; }
        public string Read_Wrtite_Access { get; set; }
        public string Processor { get; set; }
        public int Active { get; set; }
    }
}
