//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_College_Registration
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string College_Name { get; set; }
        public string College_Address { get; set; }
        public string Principal_Name { get; set; }
        public string Principal_Mobile { get; set; }
        public string Total_Students { get; set; }
        public string Total_Machines { get; set; }
        public string Total_Teachers { get; set; }
        public string IT_Teacher_Name { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public string IT_Teachers_MobileNumber1 { get; set; }
        public string IT_Teachers_Mobilenumber2 { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
