//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Password
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string B1 { get; set; }
        public string B2 { get; set; }
        public string B3 { get; set; }
        public string B4 { get; set; }
        public string B5 { get; set; }
        public string B6 { get; set; }
        public string B7 { get; set; }
        public Nullable<int> Div_Code { get; set; }
        public string Coordinator1_Name { get; set; }
        public string Coordinator1_Mobile { get; set; }
        public string Coordinator2_Name { get; set; }
        public string Coordinator2_Mobile { get; set; }
        public Nullable<int> Index_Print_Status { get; set; }
        public Nullable<int> Batch_Print_Status { get; set; }
    }
}
