//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Batch
    {
        public int Id { get; set; }
        public Nullable<int> ID_Student { get; set; }
        public string Student_Name { get; set; }
        public Nullable<int> Total_Student { get; set; }
        public Nullable<int> B1 { get; set; }
        public Nullable<int> B2 { get; set; }
        public Nullable<int> B3 { get; set; }
        public Nullable<int> B4 { get; set; }
        public Nullable<int> B5 { get; set; }
        public Nullable<int> B6 { get; set; }
    }
}
