//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Student
    {
        public int id { get; set; }
        public string seat { get; set; }
        public string div { get; set; }
        public string sch { get; set; }
        public string srno { get; set; }
        public string stream { get; set; }
        public string cent { get; set; }
        public string hand { get; set; }
        public string fresh_rpt { get; set; }
        public string reg_rpt { get; set; }
        public string medium { get; set; }
        public string cname { get; set; }
        public string mother { get; set; }
        public string sub2 { get; set; }
    }
}
