//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_31to35_Ans
    {
        public string index_no { get; set; }
        public string seat_no { get; set; }
        public string datetime { get; set; }
        public string ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q31Ans { get; set; }
        public string Q32Ans { get; set; }
        public string Q33Ans { get; set; }
        public string Q34Ans { get; set; }
        public string Q35Ans { get; set; }
    }
}
