//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_District_Co_Ordinator_Details
    {
        public int ID { get; set; }
        public Nullable<int> District_Co_Ordinator_ID { get; set; }
        public string Co_Ordinator_Name { get; set; }
        public string District_Code { get; set; }
        public string Taluka_Code { get; set; }
        public Nullable<int> Active { get; set; }
    }
}
