//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_71to75_Ans
    {
        public string index_no { get; set; }
        public string seat_no { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q71Ans { get; set; }
        public string Q72Ans { get; set; }
        public string Q73Ans { get; set; }
        public string Q74Ans { get; set; }
        public string Q75Ans { get; set; }
    }
}
