//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ITCOLLEGELIST
    {
        public int Id { get; set; }
        public string Index_No { get; set; }
        public string statusadd { get; set; }
        public string pass_sts { get; set; }
    }
}
