//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Reschedule_Student
    {
        public int ID { get; set; }
        public int Record_ID { get; set; }
        public string Index_No { get; set; }
        public string Seat_No { get; set; }
        public string Name { get; set; }
        public string Initial_Batch { get; set; }
        public string Status { get; set; }
        public string Reschedule_Batch { get; set; }
        public string Approved_By_Division { get; set; }
        public string Approved_By_OLE { get; set; }
        public string Division_Code { get; set; }
    }
}
