//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_51to55_Ans
    {
        public string index_no { get; set; }
        public string seat_no { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q51Ans { get; set; }
        public string Q52Ans { get; set; }
        public string Q53Ans { get; set; }
        public string Q54Ans { get; set; }
        public string Q55Ans { get; set; }
    }
}
