//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Decoded_Answer_Sheets_Sada
    {
        public int ID { get; set; }
        public string Seat_No { get; set; }
        public string Login_Status { get; set; }
        public string Paper_ID { get; set; }
        public string Exam_Time { get; set; }
        public string Q1ANS1 { get; set; }
        public string Q1ANS2 { get; set; }
        public string Q1ANS3 { get; set; }
        public string Q1ANS4 { get; set; }
        public string Q1ANS5 { get; set; }
        public string Q1ANS6 { get; set; }
        public string Q1ANS7 { get; set; }
        public string Q1ANS8 { get; set; }
        public string Q1ANS9 { get; set; }
        public string Q1ANS10 { get; set; }
        public string Q1ANSWERTIME { get; set; }
        public string Q2ANS1 { get; set; }
        public string Q2ANS2 { get; set; }
        public string Q2ANS3 { get; set; }
        public string Q2ANS4 { get; set; }
        public string Q2ANS5 { get; set; }
        public string Q2ANS6 { get; set; }
        public string Q2ANS7 { get; set; }
        public string Q2ANS8 { get; set; }
        public string Q2ANS9 { get; set; }
        public string Q2ANS10 { get; set; }
        public string Q2ANSWERTIME { get; set; }
        public string Q3ANS1 { get; set; }
        public string Q3ANS2 { get; set; }
        public string Q3ANS3 { get; set; }
        public string Q3ANS4 { get; set; }
        public string Q3ANS5 { get; set; }
        public string Q3ANS6 { get; set; }
        public string Q3ANS7 { get; set; }
        public string Q3ANS8 { get; set; }
        public string Q3ANS9 { get; set; }
        public string Q3ANS10 { get; set; }
        public string Q3ANSWERTIME { get; set; }
        public string Q4ANS1 { get; set; }
        public string Q4ANS2 { get; set; }
        public string Q4ANS3 { get; set; }
        public string Q4ANS4 { get; set; }
        public string Q4ANS5 { get; set; }
        public string Q4ANS6 { get; set; }
        public string Q4ANS7 { get; set; }
        public string Q4ANS8 { get; set; }
        public string Q4ANS9 { get; set; }
        public string Q4ANS10 { get; set; }
        public string Q4ANSWERTIME { get; set; }
        public string Q5ANS1 { get; set; }
        public string Q5ANS2 { get; set; }
        public string Q5ANSWERTIME { get; set; }
        public string Q6ANS1 { get; set; }
        public string Q6ANSWERTIME { get; set; }
        public string Q7ANS1 { get; set; }
        public string Q7ANS2 { get; set; }
        public string Q7ANS3 { get; set; }
        public string Q7ANS4 { get; set; }
        public string Q7ANS5 { get; set; }
        public string Q7ANS6 { get; set; }
        public string Q7ANS7 { get; set; }
        public string Q7ANS8 { get; set; }
        public string Q7ANSWERTIME { get; set; }
        public string Q8ANS1 { get; set; }
        public string Q8ANS2 { get; set; }
        public string Q8ANS3 { get; set; }
        public string Q8ANS4 { get; set; }
        public string Q8ANSWERTIME { get; set; }
    }
}
