//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_File_Upload_Details
    {
        public int ID { get; set; }
        public string Index_No { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<System.DateTime> date_Time { get; set; }
        public string Teacher_Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Id { get; set; }
        public Nullable<int> Total_Students { get; set; }
        public Nullable<int> Total_Present_Student { get; set; }
        public Nullable<int> Total_Absent_Student { get; set; }
        public Nullable<int> Text_Ans_File { get; set; }
    }
}
