//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Attendance_Web
    {
        public int ID { get; set; }
        public string Roll_No { get; set; }
        public string Batch { get; set; }
        public string Exam_Login_Status { get; set; }
        public string Paper_ID { get; set; }
        public string Attendance_Status { get; set; }
    }
}
