//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Final_Ans
    {
        public string Index_No { get; set; }
        public string Seat_No { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string Ip { get; set; }
        public string Paper_ID { get; set; }
        public string Q1_Ans { get; set; }
        public string Q_2Ans { get; set; }
        public string Q_3Ans { get; set; }
        public string Q_4Ans { get; set; }
        public string Q_5Ans { get; set; }
        public string Q_6Ans { get; set; }
        public string Q_7Ans { get; set; }
        public string Q_8Ans { get; set; }
        public string Q_9Ans { get; set; }
        public string Q_10Ans { get; set; }
        public string Q_11Ans { get; set; }
        public string Q_12Ans { get; set; }
        public string Q_13Ans { get; set; }
        public string Q_14Ans { get; set; }
        public string Q_15Ans { get; set; }
        public string Q_16Ans { get; set; }
        public string Q_17Ans { get; set; }
        public string Q_18Ans { get; set; }
        public string Q_19Ans { get; set; }
        public string Q_20Ans { get; set; }
        public string Q_21Ans { get; set; }
        public string Q_22Ans { get; set; }
        public string Q_23Ans { get; set; }
        public string Q_24Ans { get; set; }
        public string Q_25Ans { get; set; }
        public string Q_26Ans { get; set; }
        public string Q_27Ans { get; set; }
        public string Q_28Ans { get; set; }
        public string Q_29Ans { get; set; }
        public string Q_30Ans { get; set; }
        public string Q_31Ans { get; set; }
        public string Q_32Ans { get; set; }
        public string Q_33Ans { get; set; }
        public string Q_34Ans { get; set; }
        public string Q_35Ans { get; set; }
        public string Q_36Ans { get; set; }
        public string Q_37Ans { get; set; }
        public string Q_38Ans { get; set; }
        public string Q_39Ans { get; set; }
        public string Q_40Ans { get; set; }
        public string Q_41Ans { get; set; }
        public string Q_42Ans { get; set; }
        public string Q_43Ans { get; set; }
        public string Q_44Ans { get; set; }
        public string Q_45Ans { get; set; }
        public string Q_46Ans { get; set; }
        public string Q_47Ans { get; set; }
        public string Q_48Ans { get; set; }
        public string Q_49Ans { get; set; }
        public string Q_50Ans { get; set; }
        public string Q_51Ans { get; set; }
        public string Q_52Ans { get; set; }
        public string Q_53Ans { get; set; }
        public string Q_54Ans { get; set; }
        public string Q_55Ans { get; set; }
        public string Q_56Ans { get; set; }
        public string Q_57Ans { get; set; }
        public string Q_58Ans { get; set; }
        public string Q_59Ans { get; set; }
        public string Q_60Ans { get; set; }
        public string Q_61Ans { get; set; }
        public string Q_62Ans { get; set; }
        public string Q_63Ans { get; set; }
        public string Q_64Ans { get; set; }
        public string Q_65Ans { get; set; }
        public string Q_66Ans { get; set; }
        public string Q_67Ans { get; set; }
        public string Q_68Ans { get; set; }
        public string Q_69Ans { get; set; }
        public string Q_70Ans { get; set; }
        public string Q_71Ans { get; set; }
        public string Q_72Ans { get; set; }
        public string Q_73Ans { get; set; }
        public string Q_74Ans { get; set; }
        public string Q_75Ans { get; set; }
        public string Q_76Ans { get; set; }
        public string Q_77Ans { get; set; }
        public string Q_78Ans { get; set; }
        public string Q_79Ans { get; set; }
        public string Q_80Ans { get; set; }
        public string Q_81Ans { get; set; }
        public string Q_82Ans { get; set; }
        public string Q_83Ans { get; set; }
        public string Q_84Ans { get; set; }
        public string Q_85Ans { get; set; }
        public string Q_86Ans { get; set; }
        public string Q_87Ans { get; set; }
        public string Q_88Ans { get; set; }
        public string Q_89Ans { get; set; }
        public string Q_90Ans { get; set; }
        public string Q_91Ans { get; set; }
        public string Q_92Ans { get; set; }
        public string Q_93Ans { get; set; }
        public string Q_94Ans { get; set; }
        public string Q_95Ans { get; set; }
        public string Q_96Ans { get; set; }
        public string Q_97Ans { get; set; }
        public string Q_98Ans { get; set; }
        public string Q_99Ans { get; set; }
        public string Q_100Ans { get; set; }
        public int Id { get; set; }
    }
}
