//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_Info.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Inspection
    {
        public int ID { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Index_No { get; set; }
        public string SYS_No { get; set; }
        public string OS_Name { get; set; }
        public string Ram { get; set; }
        public string HDD { get; set; }
        public string MAC { get; set; }
        public string Browser_Name { get; set; }
        public string Extn_IP { get; set; }
        public string Screen_Res { get; set; }
        public string IE_Version { get; set; }
        public int Active { get; set; }
    }
}
